{"name": "test_pare[3]", "status": "failed", "statusDetails": {"message": "AssertionError: assert (1 * 1) == 3", "trace": "self = <test_case.test_func1.TestLogin object at 0x000001DC3A61ACA0>, a = 3\n\n    @pytest.mark.parametrize('a', [1, 2, 3])\n    def test_pare(self, a):\n        print('----test_pare----')\n>       assert 1 * 1 == a  # 断言\nE       assert (1 * 1) == 3\n\ntest_func1.py:21: AssertionError"}, "parameters": [{"name": "a", "value": "3"}], "start": 1611324346053, "stop": 1611324346054, "uuid": "73dcf7b7-f27b-49f6-ab21-88bc61e50d76", "historyId": "51791ac237cd7f77691838f6f33e253c", "testCaseId": "2a999addb8e1ee6be8ffc6526daab9e1", "fullName": "test_case.test_func1.TestLogin#test_pare", "labels": [{"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_func1"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "steven"}, {"name": "thread", "value": "9724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_func1"}]}